development:
  DEFAULT_URL: 'localhost:3000'
  DEVISE_PASSWORD_RESET_URL: 'localhost:3000/users/password/new'

  SECRET_KEY_BASE: '486739190b2e98d338455a2214ee504ac396d889e3081936c86830cf45f5c9b3a6598ae4d8ce0e7f527fa4818d4f896570428197d9a5f491d0cfe47b7153eb95'

  DATABASE_NAME: 'offers_sys_development'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: '1234'
  DATABASE_HOST: 'localhost'

test:
  DEFAULT_URL: 'localhost:3000'
  DEVISE_PASSWORD_RESET_URL: 'localhost:3000/users/password/new'

  SECRET_KEY_BASE: '8a35efcd2ceb4c751a862728bfd8d5a349452dabbe26125d2e9b3648cc3239dd2c852afdd99e4eb3d5469f60ebc73f3dff4a10e79285eced23a57a9fa2ee304b'

  DATABASE_NAME: 'offers_sys_test'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: '1234'
  DATABASE_HOST: 'localhost'

production:
  DEFAULT_URL: ''
  DEVISE_PASSWORD_RESET_URL: ''

  SECRET_KEY_BASE: 'd9c18925d1a3daa3702b5cce96f95d70762bae2f6115dd03ba21c094d6e125a6af945fe0f9f545d1a4a64f6f85549623932bc4dacb31f0a80359af78060d227f'

  DATABASE_NAME: 'offers_sys'
  DATABASE_USER: ''
  DATABASE_PASSWORD: ''
  DATABASE_HOST: 'localhost'
